# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-11-25 18:45
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.views.generic.base


class Migration(migrations.Migration):

    dependencies = [
        ('estante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastraLivro',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estante.Pessoa')),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            bases=(django.views.generic.base.View, 'estante.pessoa'),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
