# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-12-06 21:17
from __future__ import unicode_literals

from django.db import migrations, models
import estante.models.pessoa


class Migration(migrations.Migration):

    dependencies = [
        ('estante', '0003_auto_20181206_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.IntegerField(validators=[estante.models.pessoa.validate_phone]),
        ),
    ]
